# Generated by Django 3.1.3 on 2020-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی ')),
                ('number', models.IntegerField(verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='پیام')),
            ],
        ),
        migrations.CreateModel(
            name='requestform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی ')),
                ('number', models.IntegerField(verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('idcode', models.IntegerField(verbose_name='کد ملی')),
                ('cardnumber', models.IntegerField(verbose_name='شماره کارت')),
                ('pay', models.IntegerField(verbose_name='مبلغ به تومان')),
            ],
        ),
    ]
